# Generated by Django 6.0.6 on 2026-07-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_username_last_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_changed_username',
            field=models.BooleanField(default=False),
        ),
    ]
