# Generated by Django 6.0.6 on 2026-07-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_has_changed_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('invisible', 'Invisible'), ('away', 'Away'), ('busy', 'Busy')], default='offline', max_length=10),
        ),
    ]
